# Generated by Django 4.2.7 on 2024-11-28 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='active', max_length=10)),
                ('is_public', models.BooleanField(default=False, help_text='If checked, this capsule will be visible to everyone when unlocked.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_capsules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapsuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='capsule_contents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='capsules.timecapsule')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
