# Generated by Django 4.2.7 on 2024-12-02 12:35

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='capsule',
            field=models.ForeignKey(help_text='The time capsule this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='capsules.timecapsule'),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of content (image, video, or document)', max_length=10),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this content represents'),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=models.FileField(help_text='The actual file to be stored in the time capsule', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='capsule_contents/'),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='title',
            field=models.CharField(help_text='Title of this piece of content', max_length=200),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this content was added to the capsule'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this capsule was created'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this time capsule', on_delete=django.db.models.deletion.CASCADE, related_name='time_capsules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='description',
            field=models.TextField(blank=True, help_text='A description of what this time capsule contains or represents'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this capsule will be visible to everyone when unlocked'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='active', help_text='Current state of the capsule (active, locked, or unlocked)', max_length=10),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='title',
            field=models.CharField(help_text='The name of your time capsule', max_length=200),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='unlock_date',
            field=models.DateTimeField(help_text='When this capsule should become accessible'),
        ),
    ]
