# Generated by Django 4.2.7 on 2024-12-02 12:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_alter_capsulecontent_capsule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=models.FileField(help_text='The actual file to be stored in the time capsule', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='capsule_contents'),
        ),
    ]
