# Generated by Django 4.2.7 on 2024-12-02 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_alter_capsulecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='The actual file to be stored in the time capsule', max_length=255, verbose_name='file'),
        ),
    ]
