# Generated by Django 4.2.7 on 2024-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_alter_capsulecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image')], default='image', help_text='Type of content', max_length=20),
        ),
    ]
