# Generated by Django 4.2.7 on 2024-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_alter_capsulecontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of content (image, video, or document)', max_length=10),
        ),
    ]
